GET http://localhost:3000/poke/find_name?name=thisnorlax
Content-Type: application/json


###
GET http://localhost:3000/poke/find_id/822
Content-Type: application/json


###
GET http://localhost:3000/poke/get_all?page=2
Content-Type: application/json


###
PATCH  http://localhost:3000/poke/alterate
Content-Type: application/json

{
    "field": "generation",
    "body": "7",
    "id": "820"
}

###
POST  http://localhost:3000/poke/create
Content-Type: application/json

{
    "name": "thisnorlax",
    "pokedex_number": "3",
    "img_name": "3",
    "generation": "7",
    "evolution_stage": "2",
    "evolved": "1",
    "family_id": "1",
    "cross_gen": "0",
    "type_1": "fire",
    "type_2": "poison",
    "weather_1": "Rainy",
    "weather_2": "Cloudy",
    "stat_total": "800",
    "atk": "198",
    "def": "198",
    "sta": "160",
    "legendary": "1",
    "aquireable": "1",
    "spawns": "1",
    "regional":"0",
    "raidable":"0",
    "hatchable":"0",
    "shiny":"0",
    "nest":"0",
    "new_poke":"0",
    "not_gettable":"0",
    "future_evolve":"0",
    "cp_40":"2568",
    "cp_39":"2531"
}


###
DELETE  http://localhost:3000/poke/delete/a9e78523-12bd-46d0-810a-fd137653fac6
Content-Type: application/json
